parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'

env:
  es6: true
  browser: true
  commonjs: true

extends: 'htmlacademy/es6'

plugins: ['import-quotes']

rules:
  import-quotes/import-quotes: ['error', 'single']
  rest-spread-spacing: ['error', 'never']
  comma-dangle: ['error',
    {
      "arrays": "always-multiline",
      "objects": "always-multiline",
      "imports": "always-multiline",
      "exports": "always-multiline",
      "functions": "never"
    },
  ]
